config/routes.rb
Found::Application.routes.draw do
  default_url_options :host => "rails.iwebdev.ca"

  devise_for :users, :controllers => { :registrations => "registrations" }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'registration'}

  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin/login', :sign_out => 'admin/logout'}

  mount RailsAdmin::Engine => '/admindash', :as => 'rails_admin'
  get "home/index"
  get '/about' => 'home#about'

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'

  resources :coding_langs

  resources :project_issues

  resources :projects

  resources :home

  resources :products

  root :to => 'home#index'

end

app/models/coding_lang.rb
class CodingLang < ActiveRecord::Base
	belongs_to :project
end

app/controllers/coding_langs_controller.rb
class CodingLangsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_coding_lang, only: [:show, :edit, :update, :destroy]

  # GET /coding_langs
  # GET /coding_langs.json
  def index
    @coding_langs = CodingLang.all
  end

  # GET /coding_langs/1
  # GET /coding_langs/1.json
  def show
  end

  # GET /coding_langs/new
  def new
    @coding_lang = CodingLang.new
  end

  # GET /coding_langs/1/edit
  def edit
  end

  # POST /coding_langs
  # POST /coding_langs.json
  def create
    @coding_lang = CodingLang.new(coding_lang_params)

    respond_to do |format|
      if @coding_lang.save
        format.html { redirect_to @coding_lang, notice: 'Coding lang was successfully created.' }
        format.json { render action: 'show', status: :created, location: @coding_lang }
      else
        format.html { render action: 'new' }
        format.json { render json: @coding_lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coding_langs/1
  # PATCH/PUT /coding_langs/1.json
  def update
    respond_to do |format|
      if @coding_lang.update(coding_lang_params)
        format.html { redirect_to @coding_lang, notice: 'Coding lang was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coding_lang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coding_langs/1
  # DELETE /coding_langs/1.json
  def destroy
    @coding_lang.destroy
    respond_to do |format|
      format.html { redirect_to coding_langs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coding_lang
      @coding_lang = CodingLang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coding_lang_params
      params.require(:coding_lang).permit(:name, :description)
    end
end

app/helpers/coding_langs_helper.rb
module CodingLangsHelper
end

app/views/coding_langs/_form.html.erb
<%= form_for(coding_lang) do |f| %>
  <% if coding_lang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coding_lang.errors.count, "error") %> prohibited this coding_lang from being saved:</h2>

      <ul>
      <% coding_lang.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coding_langs/edit.html.erb
<h1>Editing coding_lang</h1>

<%= render 'form', :coding_lang => @coding_lang %>

<%= link_to 'Show', @coding_lang %> |
<%= link_to 'Back', coding_langs_path %>

app/views/coding_langs/index.html.erb
<h1>Listing coding_langs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @coding_langs.each do |coding_lang| %>
      <tr>
        <td><%= coding_lang.name %></td>
        <td><%= coding_lang.description %></td>
        <td><%= link_to 'Show', coding_lang %></td>
        <td><%= link_to 'Edit', edit_coding_lang_path(coding_lang) %></td>
        <td><%= link_to 'Destroy', coding_lang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coding lang', new_coding_lang_path %>

app/views/coding_langs/new.html.erb
<h1>New coding_lang</h1>

<%= render 'form', :coding_lang => @coding_lang %>

<%= link_to 'Back', coding_langs_path %>

app/views/coding_langs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coding_lang.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coding_lang.description %>
</p>

<%= link_to 'Edit', edit_coding_lang_path(@coding_lang) %> |
<%= link_to 'Back', coding_langs_path %>