config/routes.rb
Found::Application.routes.draw do
  default_url_options :host => "rails.iwebdev.ca"

  devise_for :users, :controllers => { :registrations => "registrations" }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'registration'}

  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin/login', :sign_out => 'admin/logout'}

  mount RailsAdmin::Engine => '/admindash', :as => 'rails_admin'
  get "home/index"
  get '/about' => 'home#about'

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'

  resources :coding_langs

  resources :project_issues

  resources :projects

  resources :home

  resources :products

  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_issues, dependent: :destroy
	has_many :products
	has_one :coding_lang
	belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.find_all_by_user_id current_user[:id]
    @project_issues = ProjectIssue.find_all_by_user_id current_user[:id]
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @issues=@project.project_issues
    @project_type = Product.find(@project.product_id).name
    @dev_lang = CodingLang.find(@project.code_lang_id).name
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)

        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :product_id, :start_date, :end_date, :notes, :code_lang_id, :description, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.text_field :name, :label => 'Project Name', :required => true, :placeholder => "Name of Project" %>
  </div>
    <div class="field">
    <%= f.text_field :notes, :label => 'Project Summary', :required => true, :placeholder => "Enter a Short Summary" %>
  </div>
  <div class="field">
    <%= f.label :product_id, "Select the type of Project" %>
    <%= f.collection_select :product_id, Product.all, :id, :name, :include_blank => false, :required => true %>
  </div>
    <div class="field">
    <%= f.label :code_lang_id, "Select the Development language" %>
    <%= f.collection_select :code_lang_id, CodingLang.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.text_area :description, :label => 'Project Description', :required => true, :placeholder => "Enter the details about your Project.", rows: 8 %>
  </div>

 <fieldset>
<legend>Project Dates</legend>
  <div class="field">
      <%= f.label :start_date, "Start Date" %>
      <div class="row date collapse" id="dp1" data-date-format="yyyy-mm-dd">
      <span class="prefix end"><input size="16" type="text" placeholder="Click to Set or Change Date" name="project[start_date]" readonly></span>
      </div>
  </div>
<br />
<br />
 <div class="field">
    <%= f.label :end_date, "Estimated End Date" %>
      <div class="row date collapse" id="dp2" data-date-format="yyyy-mm-dd">
      <span class="prefix end"><input size="16" type="text" placeholder="Click to Set or Change Date" name="project[end_date]" readonly></span>
      </div>
 </div>
 </fieldset>
  <br />
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
  <br />
<% end %>

app/views/projects/edit.html.erb
<% breadcrumb :project_edit, @edit_project_path %>
<div class="row">
<div class="medium-4 columns">
<h1><small><i class="fi-widget"></i> Editing project</small></h1>

<%= render 'form', :project => @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
<br />
<br />
</div>
</div>

app/views/projects/index.html.erb
<% breadcrumb :projects, @projects %>
<br />
<div class="row">
<!-- Left Section -->
<div class="large-6 columns">
<h3><span data-tooltip data-options="disable_for_touch:true" class="has-tip tip-top radius" title="Click on the <b>Project name</b> for more details."><i class="fi-puzzle"></i> My Project Dashboard</span></h3>
<table>
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Project Type</th>
      <th>Language</th>
      <th>Project Summary</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= Product.find(project.product_id).name %></td>
        <td><%= CodingLang.find(project.code_lang_id).name %></td>
        <td><%= project.notes %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<%= link_to 'Create a new Project', new_project_path, :class => 'small button radius' %>
</div>
<!-- Right Section -->
<div class="large-6 columns">
<h3><span data-tooltip data-options="disable_for_touch:true" class="has-tip tip-top radius" title="Click on the <b>Issue Name</b> for more details."><i class="fi-alert"></i> Open Issues</span></h3>
<table>
  <thead>
    <tr>
      <th>Issue Name</th>
      <th>Related Project</th>
      <th>Priority</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @project_issues.each do |project_issue| %>
      <tr>
        <td><%= link_to project_issue.name, project_issue %></td>
        <td><%= Project.find(project_issue.project_id).name %></td>
        <td><%= project_issue.priority.humanize %></td>
        <td><%= project_issue.status.humanize %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<br />
</div>
</div>
</div>

app/views/projects/new.html.erb
<% breadcrumb :project_new, @new_project_path %>
<div class="row">
<div class="medium-4 columns">
<h1><small><i class="fi-folder-add"></i> Add a New project</small></h1>

<%= render 'form', :project => @project %>

<%= link_to 'Back', projects_path %>
<br />
<br />
</div>
</div>

app/views/projects/show.html.erb
<% breadcrumb :project_overview, @project.name %>
<div class="row">
<div class="medium-6 columns">
<h4><i class="fi-magnifying-glass"></i> Project Overview</h4>
<div class="panel callout radius">
<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Project Summary:</strong>
  <%= @project.notes %>
</p>

<p>
  <strong>Project Type:</strong>
  <%= @project_type %>
</p>

<p>
  <strong>Development Language:</strong>
  <%= @dev_lang %>
</p>

<p>
  <strong>Project Description:</strong>
  <%= simple_format(@project.description) %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>
<ul class="button-group">
<li><%= link_to 'Edit Project', edit_project_path(@project), :class => 'tiny button success radius' %></li>
<li><%= link_to 'Back', projects_path, :class => 'tiny button success radius' %></li>
<li><%= link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure you want to delete this Project!?? Note that all associated Project Issues will be deleted as well.' }, :class => 'tiny button alert radius' %></li>
</ul>
</div>
<br />
<br />
</div>
<div class="medium-6 columns">
<h4><span data-tooltip data-options="disable_for_touch:true" class="has-tip tip-top radius" title="Click on the <b>Issue Name</b> for more details."><i class="fi-alert"></i> [<%= @project.name %>] Issues</span></h4>
<table>
  <thead>
    <tr>
      <th>Issue Name</th>
      <th>Summary</th>
      <th>Priority</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |project_issue| %>
      <tr>
        <td><%= link_to project_issue.name, project_issue %></td>
        <td> <%= project_issue.summary %></td>
        <td><%= project_issue.priority.humanize %></td>
        <td><%= project_issue.status.humanize %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to 'Create a new Issue', new_project_issue_path, :class => 'small button radius' %>
<br />
<br />
</div>